server:
   port: 8090
spring:
   datasource:
      url: jdbc:mariadb://localhost:3306/joopdatabase
      username: root
      password: joop
   jpa:
      hibernate:
         ddl-auto: update
app:
   user: joop
   pass: joopapplication2017
moss:
   userid: "567472279"
github:
   user: mariakert
   pass: Parool123
   gistlink: "https://gist.github.com/mariakert/"
mailgun:
   apikey: key-530340de58ee7be39a1358ae50b0d786
paths:
   files:
      hash: "/home/phabricator/joop/hashes/"
      plagiarism: "/home/phabricator/joop/plagiarism/"
      repos: "/home/phabricator/joop/repod/"
      zips: "/home/phabricator/joop/static/zips/"
      embeddabl: "/home/phabricator/joop/static/embeddabl/"
   scripts:
      pull: "/home/phabricator/joop/bash/pull.sh"
      hash: "/home/phabricator/joop/bash/hashcreator.sh"
      embeddabl: "/home/phabricator/joop/bash/embeddabl.sh"
      zip: "/home/phabricator/joop/bash/zipper.sh"
      copy: "/home/phabricator/joop/bash/copyfiles.sh"
      project: "/home/phabricator/joop/bash/projectcreator.sh"
   templates:
      project: "/home/phabricator/joop/templates/Template/"